let cezalar = [
    {isim : "Ağrı Kesici - Merhem - Krem", para : 100, adet: 1},
    {isim : "Ağrı Kesici - Oral - Ağız", para : 100, adet: 1},
    {isim : "Ağrı Kesici - Enjeksiyon - Serum", para : 250, adet: 1},
    {isim : "Ağrı Kesici - Anal - Fitil", para : 100, adet: 1},
    {isim : "Ağrı Kesici - Çocuk", para : 100, adet: 1},
    {isim : "Antibiyotik - Merhem - Krem", para : 100, adet: 1},
    {isim : "Antibiyotik - Oral - Ağız", para : 100, adet: 1},
    {isim : "Antibiyotik - Enjeksiyon - Serum", para : 250, adet: 1},
    {isim : "Antibiyotik - Anal - Fitil", para : 100, adet: 1},
    {isim : "Antibiyotik - Çocuk", para : 100, adet: 1},
    {isim : "Kas Gevşetici - Merhem - Krem", para : 100, adet: 1},
    {isim : "Kas Gevşetici - Oral - Ağız", para : 100, adet: 1},
    {isim : "Kas Gevşetici - Enjeksiyon - Serum", para : 250, adet: 1},
    {isim : "Kas Gevşetici - Anal - Fitil", para : 100, adet: 1},
    {isim : "Kas Gevşetici - Çocuk", para : 100, adet: 1},
    {isim : "Ayakta Müdahale", para : 1000, adet: 1},
    {isim : "Ayakta Muayne", para : 1000, adet: 1},
    {isim : "Yatılı Müdahale", para : 2500, adet: 1},
    {isim : "Yatılı Muayne", para : 2500, adet: 1},
    {isim : "Tıbbi Cerrahi Müdahale", para : 3000, adet: 1},
    {isim : "Geçici Estetik Cerrahi Müdahale", para : 0, adet: 1},
    {isim : "Kalıcı Estetik Cerrahi Müdahale", para : 10000, adet: 1},
    {isim : "Adli Vaka", para : 0, adet: 1},
    {isim : "X-Ray Bölgesel", para : 250, adet: 1},
    {isim : "X-Ray Tam Tarama", para : 500, adet: 1},
    {isim : "MRI Bölgesel", para : 250, adet: 1},
    {isim : "MRI Tam Tarama", para : 500, adet: 1},
    {isim : "Tomografi", para : 500, adet: 1},
    {isim : "Spanch", para : 100, adet: 1},
    {isim : "EKG", para : 200, adet: 1},
    {isim : "EKG - Eforlu", para : 200, adet: 1},
    {isim : "Check Up", para : 25000, adet: 1},
    {isim : "Termal Jel", para : 100, adet: 1},
    {isim : "Flaster", para : 100, adet: 1},
    {isim : "Aspirin", para : 100, adet: 1},
    {isim : "Otomatik Turnike", para : 100, adet: 1},
    {isim : "Yoğun Bakım", para : 5000, adet: 1},
    {isim : "Ex Durumu", para : 0, adet: 1},
    {isim : "Rapor - Darp", para : 10000, adet: 1},
    {isim : "Rapor - Hastalık", para : 10000, adet: 1},
    {isim : "Rapor - Tedavi", para : 10000, adet: 1},
    {isim : "Rapor - Psikiyatri", para : 10000, adet: 1},
    {isim : "Rapor - Cerrahi", para : 10000, adet: 1},
    {isim : "Rapor - Adli Vaka", para : 0, adet: 1},
    {isim : "Rapor - Mesleki Yeterlilik", para : 5000, adet: 1},
    {isim : "Rapor - Ehliyet", para : 5000, adet: 1},
    {isim : "Yanık Losyonu", para : 100, adet: 1},
    {isim : "Fizyoterapi", para : 500, adet: 1},
    {isim : "Kemoterapi", para : 1000, adet: 1},
    {isim : "Radyoterapi", para : 500, adet: 1},
    {isim : "Ortadonti", para : 10000, adet: 1},
    {isim : "Ultrasonografi", para : 5000, adet: 1},
    {isim : "Psikolojik Tedavi (Seans)", para : 2500, adet: 1},
    {isim : "Psikiyatrik Tedavi (Seans)", para : 2500, adet: 1},
    {isim : "Test - Doğum Kontrol", para : 1500, adet: 1},
    {isim : "Test - Cinsel Hastalık", para : 2000, adet: 1},
    {isim : "Test - Uyuşturucu", para : 5000, adet: 1},
    {isim : "Test - Alkol", para : 5000, adet: 1},
    {isim : "Test - DNA", para : 5000, adet: 1},

]