Config = {}

Config.Debug = false
Config.Styles = {
    [1] = { name = 'Default', value = 'default' },
    [2] = { name = 'Wounded', value = 'move_m@injured' },
    [3] = { name = 'Armored', value = 'anim_group_move_ballistic' },
    [4] = { name = 'Arrogant', value = 'move_f@arrogant@a' },
    [5] = { name = 'Brave', value = 'move_m@brave' },
    [6] = { name = 'Normal', value = 'move_f@arrogant@a' },
    [7] = { name = 'Normal 2', value = 'move_m@casual@b' },
    [8] = { name = 'Normal 3', value = 'move_m@casual@c' },
    [9] = { name = 'Normal 4', value = 'move_m@casual@d' },
    [10] = { name = 'Normal 5', value = 'move_m@casual@e' },
    [11] = { name = 'Normal 6', value = 'move_m@casual@f' },
    [12] = { name = 'Crack', value = 'move_f@chichi' },
    [13] = { name = 'Chubby', value = 'move_chubby' },
    [14] = { name = 'Chubby 2', value = 'move_f@chubby@a' },
    [15] = { name = 'Confident', value = 'move_m@confident' },
    [16] = { name = 'Police', value = 'move_m@business@a' },
    [17] = { name = 'Police 2', value = 'move_m@business@b' },
    [18] = { name = 'Police 3', value = 'move_m@business@c' },
    [19] = { name = 'Drunk', value = 'move_m@drunk@a' },
    [20] = { name = 'Drunk 2', value = 'move_m@drunk@slightlydrunk' },
    [21] = { name = 'Drunk 3', value = 'move_m@buzzed' },
    [22] = { name = 'Drunk 4', value = 'move_m@drunk@verydrunk' },
    [23] = { name = 'Femme ', value = 'move_f@femme@' },
    [24] = { name = 'Fire', value = 'move_characters@franklin@fire' },
    [25] = { name = 'Fire 2', value = 'move_characters@michael@fire' },
    [26] = { name = 'Fire 3', value = 'move_m@fire' },
    [27] = { name = 'Flee', value = 'move_f@flee@a' },
    [28] = { name = 'Franklin', value = 'move_p_m_one' },
    [29] = { name = 'Gangster', value = 'move_m@gangster@generic' },
    [30] = { name = 'Gangster 2', value = 'move_m@gangster@ng' },
    [31] = { name = 'Gangster 3', value = 'move_m@gangster@var_e' },
    [32] = { name = 'Gangster 4', value = 'move_m@gangster@var_f' },
    [33] = { name = 'Gangster 5', value = 'move_m@gangster@var_i' },
    [34] = { name = 'Grooving', value = 'anim@move_m@grooving@' },
    [35] = { name = 'Koruma', value = 'move_m@prison_gaurd' },
    [36] = { name = 'Heel', value = 'move_f@heels@c' },
    [37] = { name = 'Heel 2', value = 'move_f@heels@d' },
    [38] = { name = 'Hiking', value = 'move_m@hiking' },
    [39] = { name = 'Hipster', value = 'move_m@hipster@a' },
    [40] = { name = 'Hobo', value = 'move_m@hobo@a' },
    [41] = { name = 'Hurry', value = 'move_f@hurry@a' },
    [42] = { name = 'Alien', value = 'move_m@alien' },
    [43] = { name = 'Janitor', value = 'move_p_m_zero_janitor' },
    [44] = { name = 'Janitor 2', value = 'move_p_m_zero_janitor' },
    [45] = { name = 'Maneater', value = 'move_f@maneater' },
    [46] = { name = 'Money', value = 'move_m@money' },
    [47] = { name = 'Muscle', value = 'move_m@muscle@a' },
    [48] = { name = 'Cold-blooded', value = 'move_m@non_chalant' },
    [49] = { name = 'Fast', value = 'move_m@quick' },
    [50] = { name = 'Sad', value = 'move_m@sad@a' },
    [51] = { name = 'Sassy', value = 'move_m@sassy' },
    [52] = { name = 'Scared', value = 'move_f@scared' },
    [53] = { name = 'Shady', value = 'move_m@shadyped@a' },
    [54] = { name = 'Swagger', value = 'move_m@swagger' },
    [55] = { name = 'Tough', value = 'move_m@tough_guy@' },
    [56] = { name = 'Tough 2', value = 'move_f@tough_guy@' },
    [57] = { name = 'Wave the Arms', value = 'move_m@bag' },
}

